DROP TABLE IF EXISTS log CASCADE;
DROP TABLE IF EXISTS new_top_50_products CASCADE;
DROP TABLE IF EXISTS old_top_5_products CASCADE;
DROP TABLE IF EXISTS top_state_sales CASCADE;
DROP TABLE IF EXISTS top_product_sales CASCADE;
DROP TABLE IF EXISTS precomputed_state_topk CASCADE;
DROP TABLE IF EXISTS top_state_sales_filtered CASCADE;
DROP TABLE IF EXISTS top_product_sales_filtered CASCADE;
DROP TABLE IF EXISTS precomputed_state_topk_filtered CASCADE;